### ISSUE TITLE
Yeti in the Nether

### ISSUE THREAD

**Issue by Ataron** [Ombridride/minetest-minetestforfun-server#101]
I was with palige in the Nether, and because of the old bug of snow, some snow was still on netherrack. Then, Yeti spawned on the snow and kill me. I don't think Yeti is the better monster for the Nether so maybe we can make a limit of spawn like -100 ?

**Comment by Ombridride** [comment]
Normal, long time ago there was falling snow in the Nether,
It's fixed since a long time BUT snow nodes still in the Nether AND Yetis spawn on snow nodes.

It's unnecessary to add a spawn restriction on more mobs, wich will reduce the possibilities for players => So, just dig the snow nodes remaining...
