### ISSUE TITLE
New [Commerce_Machines] Mod

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#49]
Add this mod to the server ? https://forum.minetest.net/viewtopic.php?f=11&t=11195&hilit=Money

This mod is a revised fork based on our old Money mod. This machines are more easy to use and are more beautiful, the mod is maintained by jp.

![Image 1](http://i.imgur.com/vd4cLGv.jpg)

We need to comment the parts with commands like "/money", because it's not useful for us. (our money is coins, and this machines are here for trade between players) Maybe also delete the fields in formspec which call money values.

![Image 1](https://lut.im/dtJeFwMO/u5oWQOwP)

(Don't forget to change the world.mt and the ~/misc/aliases.lua file)

**Comment by Ombridride** [comment]
@LeMagnesium you lastest merge about the __money machines_ is it linked with this issue ?

**Comment by Ombridride** [comment]
@LeMagnesium
Please, can you answer to the last question ...?

**Comment by LeMagnesium** [comment]
The merge is there : https://github.com/Ombridride/minetest-minetestforfun-server/commit/8acd6b66b999a0da76212940625d406d024e2ccb

It's kind of pointless because the only mechanism added cannot be transposed for the barter shops, and we don't use any other kind of shops. I just added new textures I think.

**Comment by Ombridride** [comment]
Ok
