### ISSUE TITLE
Minor boot errors

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#86]
Some minor boot errors wich need to be fix :

```
----------------------
Server restarted at lundi 8 juin 2015, 21:58:54 (UTC+0200)
----------------------
WARNING: system-wide share not found at "/usr/share/minetest"
WARNING: system-wide share not found at "/home/quentinbd/minetest/bin/../share/minetest"
WARNING: system-wide share found at "/home/quentinbd/minetest/bin/.."
Using game specified by --gameid on the command line
21:58:54: ERROR[main]: The following mods could not be found: "tetris"
.....
21:58:54: WARNING: Undeclared global variable "handlers" accessed at ...home/quentinbd/minetest/bin/../mods/irc/irc/main.lua:188
.....
```

**Comment by LeMagnesium** [comment]
I can do something about the global variable and tetris, but sadly, the warnings at the beginning won't disappear, they are always shown for self-compiled binaries.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/412ab2986beafd15f472eec3dfea64011d0f3d14

We're probably using an old version of our IRC mod's backup, because `handlers` is already fixed : [see the file](https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/other_things/irc-old-save/irc/main.lua#L188).

**Comment by Ombridride** [comment]
Yes, i closed the issue, when the IRC mod will be updated, the error will be fixed
